version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Test"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/Core"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/WebApp"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/WebApp/ClientApp"
    schedule:
      interval: "daily"     
